steps:
  - block: "Distribute"
    input: "Who is running this script?"
    fields:
      - select: "Your flavor"
        key: "distribute-flavor"
        required: true
        options:
          - label: "Internal"
            value: "internal"
          - label: "Production"
            value: "production"
      - select: "Delivery address"
        key: "distribute-destination"
        required: true
        options:
          - label: "Firebase"
            value: "firebase"
          - label: "Google Play Store internal track"
            value: "playstore"      
  - label: "Run script"
    command: script.sh
